# Generated by Django 4.1.1 on 2022-09-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tech',
            new_name='category_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='usecase',
            field=models.CharField(max_length=100),
        ),
    ]
