# Generated by Django 4.1.1 on 2022-09-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_tech_news_category_id_alter_category_usecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Rafael Cazarotto', max_length=100),
            preserve_default=False,
        ),
    ]
